export const COMPANY_LOAD_REQUEST = "COMPANY_LOAD_REQUEST";
export const COMPANY_LOAD_SUCCESS = "COMPANY_LOAD_SUCCESS";
export const COMPANY_LOAD_FAIL = "COMPANY_LOAD_FAIL";
export const COMPANY_LOAD_RESET = "COMPANY_LOAD_RESET";


export const COMPANY_LOAD_SINGLE_REQUEST = "COMPANY_LOAD_SINGLE_REQUEST";
export const COMPANY_LOAD_SINGLE_SUCCESS = "COMPANY_LOAD_SINGLE_SUCCESS";
export const COMPANY_LOAD_SINGLE_FAIL = "COMPANY_LOAD_SINGLE_FAIL";
export const COMPANY_LOAD_SINGLE_RESET = "COMPANY_LOAD_SINGLE_RESET";

export const REGISTER_COMPANY_REQUEST = "REGISTER_COMPANY_REQUEST";
export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS";
export const REGISTER_COMPANY_FAIL = "REGISTER_COMPANY_FAIL";
export const REGISTER_COMPANY_RESET = "REGISTER_COMPANY_RESET";

export const DELETE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "CREATE_COMPANY_FAIL";
export const DELETE_COMPANY_RESET = "CREATE_COMPANY_RESET";

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL";
export const UPDATE_COMPANY_RESET = "UPDATE_COMPANY_RESET";